"""
cookie_harvest.py — Playwright-based cookie harvester for MMI.

Visits a curated list of websites using a real Chromium browser, collects
cookies, and writes them in Netscape cookies.txt format for yt-dlp to consume.

The most important visits are the target sites themselves (rumble.com etc.)
so their anti-bot challenge cookies are captured. Popular sites are visited
first to build a realistic browsing profile before hitting protected sites.

Usage:
    python -m mmi.cookie_harvest              # saves to MMI_OUTPUT_DIR/cookies.txt
    python -m mmi.cookie_harvest /custom/path/cookies.txt
"""
from __future__ import annotations

import sys
import time
from pathlib import Path

from mmi.config import MMI_OUTPUT_DIR, get_logger

logger = get_logger("mmi.cookie_harvest")

# Sites to visit in order — popular/trusted sites first to build a realistic
# profile, then the actual target sites we want cookies for.
HARVEST_SITES = [
    # Warm-up: establish a real-looking browsing history
    "https://www.google.com",
    "https://www.youtube.com",
    "https://www.reddit.com",
    "https://www.wikipedia.org",
    "https://www.cnn.com",
    "https://www.bbc.com",
    "https://www.twitter.com",
    # Target sites — visiting these is the actual goal
    "https://rumble.com",
    "https://rumble.com/videos",
    "https://odysee.com",
]

# How long to dwell on each page (seconds) so JS/cookie challenges can run
DWELL_SECONDS = 3


def _to_netscape(cookies: list[dict]) -> str:
    """Convert Playwright cookie dicts to Netscape cookies.txt format."""
    lines = ["# Netscape HTTP Cookie File", "# Generated by mmi.cookie_harvest", ""]
    for c in cookies:
        domain = c.get("domain", "")
        # Netscape format: domains not starting with '.' need one for subdomains
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        # Use a far-future expiry for session cookies (0 or -1 means session)
        expires = int(c.get("expires", -1))
        if expires <= 0:
            expires = 2147483647  # 2038 — yt-dlp treats 0 as expired
        name = c.get("name", "")
        value = c.get("value", "")
        if name:  # skip nameless cookies
            lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines) + "\n"


def harvest_cookies(output_path: Path | None = None, headless: bool = True) -> Path:
    """
    Launch Chromium, visit HARVEST_SITES, and write cookies to output_path.

    Args:
        output_path: Where to write cookies.txt. Defaults to MMI_OUTPUT_DIR/cookies.txt.
        headless:    Run browser headlessly (True) or visibly (False).

    Returns:
        Path to the written cookies file.
    """
    from playwright.sync_api import sync_playwright

    if output_path is None:
        MMI_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        output_path = MMI_OUTPUT_DIR / "cookies.txt"

    output_path.parent.mkdir(parents=True, exist_ok=True)

    logger.info("Starting cookie harvest — %d sites to visit", len(HARVEST_SITES))

    with sync_playwright() as pw:
        browser = pw.chromium.launch(
            headless=headless,
            args=[
                "--disable-blink-features=AutomationControlled",  # hide webdriver flag
                "--no-sandbox",
            ],
        )
        context = browser.new_context(
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/124.0.0.0 Safari/537.36"
            ),
            viewport={"width": 1280, "height": 800},
            locale="en-US",
        )
        page = context.new_page()

        for url in HARVEST_SITES:
            try:
                logger.info("Visiting %s ...", url)
                page.goto(url, wait_until="domcontentloaded", timeout=20_000)
                # Scroll to trigger lazy-loaded content and cookie banners
                page.evaluate("window.scrollTo(0, document.body.scrollHeight / 3)")
                time.sleep(DWELL_SECONDS)
            except Exception as exc:
                logger.warning("Failed to load %s: %s", url, exc)

        all_cookies = context.cookies()
        browser.close()

    logger.info("Collected %d cookies from %d sites", len(all_cookies), len(HARVEST_SITES))

    netscape_text = _to_netscape(all_cookies)
    output_path.write_text(netscape_text, encoding="utf-8")
    logger.info("Cookies written to %s", output_path)

    return output_path


if __name__ == "__main__":
    path_arg = Path(sys.argv[1]) if len(sys.argv) > 1 else None
    result = harvest_cookies(output_path=path_arg)
    print(f"Cookies saved to: {result}")
    print(f"Lines: {len(result.read_text(encoding='utf-8').splitlines())}")
